version: '3.8'

services:

  mongodb:
    image: mongo:7.0
    container_name: analytics-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: analytics123
      MONGO_INITDB_DATABASE: analytics
    volumes:
      - mongodb_data:/data/db

  analytics-server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: analytics-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://premachawada1_db_user:BeOHRAlunlIdkSm5@ac-ere1lvi-shard-00-00.jaxr3tw.mongodb.net:27017,ac-ere1lvi-shard-00-01.jaxr3tw.mongodb.net:27017,ac-ere1lvi-shard-00-02.jaxr3tw.mongodb.net:27017/ecommerce?ssl=true&authSource=admin&retryWrites=true&w=majority
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb

  analytics-client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    container_name: analytics-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_WS_URL=http://localhost:4000
    depends_on:
      - analytics-server

volumes:
  mongodb_data:
